package veterinaria.reportes.core;

public enum ReporteTipo {
    RECIBO_VENTA,
    COMPRA_RECEPCION,
    CC_COBRO,
    CC_MOVIMIENTOS,
    CC_LISTA_CUENTAS,
    LABORATORIO_INFORME,
    HOSPITALIZACION_REGISTRO,
    HISTORIAL_TURNOS,
    HISTORIAL_TURNOS_LISTADO,

    USUARIO_REGISTRO,
    USUARIO_LISTADO,

    MASCOTA_REGISTRO,
    MASCOTA_LISTADO,

    CLIENTE_REGISTRO,
    CLIENTE_LISTADO,

    PRODUCTO_REGISTRO,
    PRODUCTO_LISTADO,

    STOCK_PRODUCTO_REGISTRO,
    STOCK_PRODUCTO_LISTADO,

    PROVEEDOR_REGISTRO,
    PROVEEDOR_LISTADO,

    VISITA_REGISTRO,
    VISITA_LISTADO,

    HISTORIA_CLINICA,
    HISTORIA_CLINICA_LISTADO,

    CAJA_MOVIMIENTO,
    CAJA_MOVIMIENTOS_LISTADO,

    AUDITORIA_EVENTO,
    AUDITORIA_LISTADO
}