
package veterinaria.vista;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import veterinaria.controlador.ClienteControlador;
import veterinaria.controlador.CuentaCorrienteControlador;
import veterinaria.entidad.Cliente;
import veterinaria.entidad.CuentaCorriente;
import veterinaria.util.ManejoTablas;
import veterinaria.util.SesionUsuario;
import veterinaria.vista.application.Application;
import veterinaria.util.PermisoUI;

public class FormGestionCuentasCorrientes extends javax.swing.JPanel {
    private SesionUsuario sesion = Application.getSesionUsuario();

    private List<Map.Entry<Integer, String>> listaClientes = new ArrayList<>();
    private final ClienteControlador operarClientes = new ClienteControlador();
    private final CuentaCorrienteControlador operarCuentaCorriente = new CuentaCorrienteControlador();
    private final ManejoTablas operarTabla = new ManejoTablas();
    private CuentaCorriente cuentaCorriente = new CuentaCorriente();
    private Cliente cliente = new Cliente();
    private ManejoTablas operarTablas = new ManejoTablas();
    private boolean listenerClienteInstalado = false;
    private boolean permitirRecalculoMasivo = false;
    
    public FormGestionCuentasCorrientes() {
        initComponents();
        PermisoUI.aplicar(this);
        // Permisos por RBAC (sin hardcodear rol)
        String permActualizar = "FormGestionCuentasCorrientes.ACTUALIZAR_SALDOS";
        permitirRecalculoMasivo = (sesion != null && sesion.puede(permActualizar));
        if (permitirRecalculoMasivo) {
            // Mantener el comportamiento actual, pero el recálculo se hace fuera del EDT.
            jpDatosCuentaCorriente.setVisible(false);
        }
        initListeners();
        cargarInicialAsync();
    }

    private void setBusy(boolean busy) {
        try {
            setCursor(busy ? java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR)
                           : java.awt.Cursor.getDefaultCursor());
        } catch (Exception ignored) {
        }
    }

    private void cargarInicialAsync() {
        setBusy(true);
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                if (permitirRecalculoMasivo) {
                    operarCuentaCorriente.actualizarTodosLosSaldosCC();
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    cargarComboClientesTodosAsync();
                    cargarCuentasCorrientesEnTablaAsync();
                } finally {
                    setBusy(false);
                }
            }
        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbUsuarioBusqueda = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jpDatosCuentaCorriente = new javax.swing.JPanel();
        lbDatosCuenta = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        txtSaldoInicial = new javax.swing.JTextField();
        lbSaldoInicial = new javax.swing.JLabel();
        txtLimiteDeCredito = new javax.swing.JTextField();
        lbLimiteDeCredito = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        lbEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jcbCliente = new javax.swing.JComboBox<>();
        panelLista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        tableCCClientes = new veterinaria.vista.table.AutoTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cuenta Corriente");

        lbUsuarioBusqueda.setText("Cuenta");

        lbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/icon/png/search.png"))); // NOI18N

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHeaderLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(panelHeaderLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbUsuarioBusqueda)))
                        .addGap(0, 707, Short.MAX_VALUE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(panelHeaderLayout.createSequentialGroup()
                                .addComponent(lbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuarioBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbBuscar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbDatosCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDatosCuenta.setText("Datos cuenta");

        lbCliente.setText("Cliente");

        lbSaldoInicial.setText("Saldo Inicial");

        lbLimiteDeCredito.setText("Limite de Credito");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Estado:", "Activa", "Inactiva" }));

        lbEstado.setText("Estado");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jcbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Cliente:" }));

        javax.swing.GroupLayout jpDatosCuentaCorrienteLayout = new javax.swing.GroupLayout(jpDatosCuentaCorriente);
        jpDatosCuentaCorriente.setLayout(jpDatosCuentaCorrienteLayout);
        jpDatosCuentaCorrienteLayout.setHorizontalGroup(
            jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                        .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbDatosCuenta))
                            .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSaldoInicial)
                                    .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLimiteDeCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbLimiteDeCredito))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado))))
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosCuentaCorrienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpDatosCuentaCorrienteLayout.setVerticalGroup(
            jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                        .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSaldoInicial)
                            .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbLimiteDeCredito)
                                .addComponent(lbEstado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpDatosCuentaCorrienteLayout.createSequentialGroup()
                        .addComponent(lbDatosCuenta)
                        .addGap(18, 18, 18)
                        .addComponent(lbCliente)
                        .addGap(6, 6, 6)))
                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimiteDeCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jpDatosCuentaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tableCCClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seleccionar", "Núm. de Cuenta", "Cliente", "Saldo Actual", "Limite", "Fecha Creación", "Ultima Edición", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCCClientes.setMinimumSize(new java.awt.Dimension(848, 220));
        tableCCClientes.setPreferredSize(new java.awt.Dimension(848, 220));
        tableCCClientes.getTableHeader().setReorderingAllowed(false);
        scroll.setViewportView(tableCCClientes);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(scroll)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpDatosCuentaCorriente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDatosCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initListeners(){
        List<Integer> columnasObjetivo = Arrays.asList(1, 2, 3, 6, 7);
        operarTablas.aplicarFiltroYResaltado(tableCCClientes, txtBusqueda, columnasObjetivo);   

    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String perm = "FormGestionCuentasCorrientes.ELIMINAR";
        if (sesion == null || !sesion.puede(perm)) {
            JOptionPane.showMessageDialog(
                    null,
                    "No tienes permisos suficientes para eliminar cuentas corrientes.",
                    "Acceso restringido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Application.actualizarEstadoUsuario("EliminandoCuentaCorriente");
        int respuesta = JOptionPane.showConfirmDialog(
            this, "¿Estás seguro de que deseas eliminar esta Cuenta Corriente?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            Application.actualizarEstadoUsuario("Eliminanda");
            eliminarCuentaCorrienteSeleccionada();
            limpiarCamposFormulario();
            jpDatosCuentaCorriente.setVisible(false);
            cargarCuentasCorrientesEnTablaAsync();
        } else {
            Application.actualizarEstadoUsuario("Eliminación cancelada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        jcbCliente.setEnabled(false);
        txtSaldoInicial.setEnabled(false);
        String perm = "FormGestionCuentasCorrientes.EDITAR";
        if (sesion != null && sesion.puede(perm)) {
            if (editarCuentaCorrienteSeleccionada()){
                Application.actualizarEstadoUsuario("EditandoCuentaCorriente");
                jpDatosCuentaCorriente.setVisible(true);
                btnNuevo.setEnabled(false);
                btnEditar.setEnabled(false);
                btnEliminar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "No tienes permisos suficientes para editar cuentas corrientes.",
                    "Acceso restringido",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Application.actualizarEstadoUsuario("CreandoCuentaCorriente");
        jpDatosCuentaCorriente.setVisible(true);
        panelLista.setEnabled(false);
        txtSaldoInicial.setText("0");
        txtLimiteDeCredito.setText("100000");
        cargarComboClientesParaCrearCC();
        
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(validarDatosCuentaCorriente()){
            // Confirmación explícita (Sí/No) + resumen antes de crear/editar
            if (!confirmarGuardarCuentaCorriente()) {
                Application.actualizarEstadoUsuario("Operación cancelada");
                return;
            }

            persistirCuentaCorriente();
            limpiarCamposFormulario();
            jpDatosCuentaCorriente.setVisible(false);
            panelLista.setVisible(true);
            btnNuevo.setEnabled(true);
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
            initListeners();
            cargarComboClientesTodosAsync();
            cargarCuentasCorrientesEnTablaAsync();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCamposFormulario();
        initListeners();
        cargarComboClientesTodosAsync();
        cargarCuentasCorrientesEnTablaAsync();
        jpDatosCuentaCorriente.setVisible(false);
        panelLista.setVisible(true);
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cargarCombosBoxs(){
        List<Cliente> clientes = operarClientes.buscarTodosLosClientes();
        if(jcbEstado.getSelectedIndex() == -1 ){
            jcbEstado.addItem("Seleccione un estado:");
            jcbEstado.addItem("Activa");
            jcbEstado.addItem("Inactiva");
        }
        for (Cliente clienteBucle : clientes) {
            Integer idCliente = clienteBucle.getIdCliente();
            String nombreCliente = clienteBucle.getPersona().getNombre() + " " + clienteBucle.getPersona().getApellido();
            listaClientes.add(new AbstractMap.SimpleEntry<>(idCliente, nombreCliente));
        }
        for (Map.Entry<Integer, String> entry : listaClientes) {
            jcbCliente.addItem(entry.getValue());
        }
        jcbCliente.addActionListener(e -> enClienteSeleccionado());
    }

    private void enClienteSeleccionado(){
        String pacienteSelec = (String) jcbCliente.getSelectedItem();
        cliente = new Cliente();
        
        if (pacienteSelec != null && pacienteSelec != "Seleccionar Cliente:" ) {
            for (Map.Entry<Integer, String> entry : listaClientes) {
                if (entry.getValue().equals(pacienteSelec)) {
                    cliente = operarClientes.buscarPorId(entry.getKey());
                    break;
                }
            }
        }
    }
    
    private void limpiarCamposFormulario(){
        txtSaldoInicial.setText("");
        txtLimiteDeCredito.setText("");
        jcbEstado.removeAllItems();
        jcbCliente.removeAllItems();
        txtBusqueda.setText("");
        cargarCombosBoxs();        
    }

    private void eliminarCuentaCorrienteSeleccionada(){
        int selectedRow = operarTabla.comprobarElementoSeleccionado(tableCCClientes);
        if (selectedRow != -1) {
            var idCuentaCorriente = (Integer) tableCCClientes.getValueAt(selectedRow, 1);
            cuentaCorriente = operarCuentaCorriente.buscarCuentaCorrientePorId(idCuentaCorriente);

            int r = JOptionPane.showConfirmDialog(
                    this,
                    "Las Cuentas Corrientes NO se eliminan.\n\n" +
                    "Se marcará como INACTIVA para impedir su uso desde Caja.\n" +
                    "El historial y movimientos se conservarán.\n\n" +
                    "¿Desea desactivar la cuenta seleccionada?",
                    "Confirmar desactivación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            if (r == JOptionPane.YES_OPTION) {
                if (operarCuentaCorriente.desactivarCuentaCorriente(cuentaCorriente)) {
                    JOptionPane.showMessageDialog(null, "Cuenta Corriente desactivada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo desactivar la Cuenta Corriente", "Error", JOptionPane.ERROR_MESSAGE);
                }
                cargarCuentasCorrientesEnTablaAsync();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una Cuenta Corriente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cargarCuentasCorrientesEnTablaAsync() {
        setBusy(true);
        new SwingWorker<List<Object[]>, Void>() {
            @Override
            protected List<Object[]> doInBackground() {
                List<CuentaCorriente> cuentasCorrientes = operarCuentaCorriente.buscarTodasLasCuentasCorrientes();
                ArrayList<Object[]> filas = new ArrayList<>();
                for (CuentaCorriente cc : cuentasCorrientes) {
                    Cliente c = operarClientes.buscarPorId(cc.getCliente().getIdCliente());
                    Object nombreCliente = (c != null && c.getPersona() != null)
                            ? (c.getPersona().getNombre() + " " + c.getPersona().getApellido())
                            : "";
                    filas.add(new Object[]{
                        false,
                        cc.getIdCuentaCorriente(),
                        nombreCliente,
                        cc.getSaldoActual(),
                        cc.getLimiteCredito(),
                        cc.getFechaCreacion(),
                        cc.getUltimaEdicion(),
                        cc.getEstado(),
                    });
                }
                return filas;
            }

            @Override
            protected void done() {
                try {
                    List<Object[]> filas = get();
                    DefaultTableModel modelo = (DefaultTableModel) tableCCClientes.getModel();
                    modelo.setRowCount(0);
                    for (Object[] f : filas) {
                        modelo.addRow(f);
                    }
                    operarTabla.asegurarSeleccionUnica(tableCCClientes);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(FormGestionCuentasCorrientes.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    setBusy(false);
                }
            }
        }.execute();
    }
    
    private void cargarCuentasCorrientesEnTabla(){
        List<CuentaCorriente> cuentasCorrientes = operarCuentaCorriente.buscarTodasLasCuentasCorrientes();
        DefaultTableModel modelo = (DefaultTableModel) tableCCClientes.getModel();
        modelo.setRowCount(0);

        for (CuentaCorriente cuentaCorrienteBucle : cuentasCorrientes) {
            Cliente cliente = operarClientes.buscarPorId(cuentaCorrienteBucle.getCliente().getIdCliente());
            Object nombreCliente = cliente.getPersona().getNombre() + " " + cliente.getPersona().getApellido();
            Object[] fila = new Object[]{
                false,
                cuentaCorrienteBucle.getIdCuentaCorriente(),
                nombreCliente,
                cuentaCorrienteBucle.getSaldoActual(),
                cuentaCorrienteBucle.getLimiteCredito(), // ✅ NUEVO: columna "Limite"
                cuentaCorrienteBucle.getFechaCreacion(),
                cuentaCorrienteBucle.getUltimaEdicion(),
                cuentaCorrienteBucle.getEstado(),
            };
            modelo.addRow(fila);
        }
        operarTabla.asegurarSeleccionUnica(tableCCClientes);        
    }

    private boolean validarDatosCuentaCorriente(){
        if (jcbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente!");
            return false;
        }
        if (txtSaldoInicial.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El saldo inicial no puede estar vacío.");
            return false;
        }
        if (txtLimiteDeCredito.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un limite de crédito!");
            return false;
        }

        BigDecimal saldoInicial;
        BigDecimal limiteCredito;
        try {
            saldoInicial = parsearMonto(txtSaldoInicial.getText(), "saldo inicial");
            limiteCredito = parsearMonto(txtLimiteDeCredito.getText(), "límite de crédito");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Dato inválido", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (saldoInicial.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "El saldo inicial no puede ser negativo.");
            return false;
        }
        if (limiteCredito.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "El límite de crédito no puede ser negativo.");
            return false;
        }

        if (jcbEstado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado de Cuenta Corriente!");
            return false;
        }
        return true;          
    }

    private BigDecimal parsearMonto(String valor, String nombreCampo) {
        String normalizado = valor != null ? valor.trim().replace(" ", "").replace(",", ".") : "";
        if (normalizado.isEmpty()) {
            throw new NumberFormatException("El campo " + nombreCampo + " no puede estar vacío.");
        }
        try {
            return new BigDecimal(normalizado);
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El campo " + nombreCampo + " debe contener un monto numérico válido.");
        }
    }

    private void persistirCuentaCorriente() {
        boolean creando = "CreandoCuentaCorriente".equals(Application.consultarEstadoUsuario());
        boolean editando = "EditandoCuentaCorriente".equals(Application.consultarEstadoUsuario());

        if (creando) {
            cuentaCorriente = new CuentaCorriente();
            cuentaCorriente.setFechaCreacion(LocalDate.now());
            // Al crear: saldo actual inicia en 0 (según tu lógica actual)
            cuentaCorriente.setSaldoActual(new BigDecimal(0));
        }

        BigDecimal saldoInicial = parsearMonto(txtSaldoInicial.getText(), "saldo inicial");
        BigDecimal limiteCredito = parsearMonto(txtLimiteDeCredito.getText(), "límite de crédito");

        // Datos que aplican tanto a crear como a editar
        cuentaCorriente.setCliente(cliente);
        cuentaCorriente.setSaldoInicial(saldoInicial);
        cuentaCorriente.setLimiteCredito(limiteCredito);
        cuentaCorriente.setUltimaEdicion(LocalDate.now());
        cuentaCorriente.setEstado(jcbEstado.getSelectedItem().toString());

        // En edición NO tocar saldoActual ni fechaCreacion (se preservan)
        if (creando) {
            try {
                if (operarCuentaCorriente.crearCuentaCorriente(cuentaCorriente)) {
                    JOptionPane.showMessageDialog(this, "Cuenta Corriente creada exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar una Cuenta Corriente!");
                }
            } catch (Exception ex) {
                Logger.getLogger(FormGestionCuentasCorrientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (editando) {
            try {
                operarCuentaCorriente.actualizarCuentaCorriente(cuentaCorriente);
                JOptionPane.showMessageDialog(this, "Cuenta Corriente editada exitosamente.");
            } catch (Exception ex) {
                Logger.getLogger(FormGestionCuentasCorrientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * Muestra una confirmación Sí/No con resumen de datos.
     * Evita guardados involuntarios al crear o editar.
     */
    private boolean confirmarGuardarCuentaCorriente() {
        boolean creando = "CreandoCuentaCorriente".equals(Application.consultarEstadoUsuario());
        boolean editando = "EditandoCuentaCorriente".equals(Application.consultarEstadoUsuario());

        String accion = creando ? "CREAR" : (editando ? "EDITAR" : "GUARDAR");
        String titulo = creando ? "Confirmar creación" : (editando ? "Confirmar edición" : "Confirmar");

        String clienteTxt = (String) jcbCliente.getSelectedItem();
        String saldoInicialTxt = txtSaldoInicial.getText() != null ? txtSaldoInicial.getText().trim() : "";
        String limiteTxt = txtLimiteDeCredito.getText() != null ? txtLimiteDeCredito.getText().trim() : "";
        String estadoTxt = (jcbEstado.getSelectedItem() != null) ? jcbEstado.getSelectedItem().toString() : "";

        StringBuilder sb = new StringBuilder();
        sb.append("Estás por ").append(accion).append(" una Cuenta Corriente.\n\n");
        if (editando && cuentaCorriente != null && cuentaCorriente.getIdCuentaCorriente() != null) {
            sb.append("N° de cuenta: ").append(cuentaCorriente.getIdCuentaCorriente()).append("\n");
        }
        sb.append("Cliente: ").append(clienteTxt != null ? clienteTxt : "").append("\n");
        sb.append("Saldo inicial: ").append(saldoInicialTxt).append("\n");
        sb.append("Límite de crédito: ").append(limiteTxt).append("\n");
        sb.append("Estado: ").append(estadoTxt).append("\n\n");
        sb.append("¿Confirmás la operación?");

        Object[] opciones = new Object[]{"Sí", "No"};
        int r = JOptionPane.showOptionDialog(
                this,
                sb.toString(),
                titulo,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                "No"
        );
        return r == 0; // 0 = "Sí"
    }
    
    private boolean editarCuentaCorrienteSeleccionada() {
        boolean bRetorno = false;
        int selectedRow = operarTabla.comprobarElementoSeleccionado(tableCCClientes);

        if (selectedRow != -1) {
            Integer cuentaSelec = (Integer) tableCCClientes.getValueAt(selectedRow, 1);

            cuentaCorriente = operarCuentaCorriente.buscarCuentaCorrientePorId(cuentaSelec);

            Integer idCliente = cuentaCorriente.getCliente().getIdCliente();

            // Seleccionar el cliente en el combo por ID (no por texto)
            int idx = -1;
            for (int i = 0; i < listaClientes.size(); i++) {
                if (listaClientes.get(i).getKey().equals(idCliente)) {
                    idx = i;
                    break;
                }
            }

            if (idx >= 0) {
                jcbCliente.setSelectedIndex(idx + 1); // +1 por "Seleccionar Cliente:"
            } else {
                jcbCliente.setSelectedIndex(0);
            }

            // En edición, conviene bloquear el cliente (no debería cambiarse)
            jcbCliente.setEnabled(false);

            txtSaldoInicial.setText(String.valueOf(cuentaCorriente.getSaldoInicial()));
            txtLimiteDeCredito.setText(String.valueOf(cuentaCorriente.getLimiteCredito()));
            jcbEstado.setSelectedItem(cuentaCorriente.getEstado());

            bRetorno = true;
        }
        return bRetorno;
    }


    private void cargarComboClientesParaCrearCC() {
        // SOLO clientes sin CC
        List<Cliente> clientes = operarClientes.buscarClientesSinCuentaCorriente();
        recargarComboClientes(clientes);
    }

    private void cargarComboClientesTodos() {
        // Para edición/listado (si lo necesitás)
        List<Cliente> clientes = operarClientes.buscarTodosLosClientes();
        recargarComboClientes(clientes);
    }

    private void cargarComboClientesTodosAsync() {
        setBusy(true);
        new SwingWorker<List<Cliente>, Void>() {
            @Override
            protected List<Cliente> doInBackground() {
                return operarClientes.buscarTodosLosClientes();
            }

            @Override
            protected void done() {
                try {
                    recargarComboClientes(get());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(FormGestionCuentasCorrientes.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    setBusy(false);
                }
            }
        }.execute();
    }

    private void recargarComboClientes(List<Cliente> clientes) {
        listaClientes.clear();
        jcbCliente.removeAllItems();
        jcbCliente.addItem("Seleccionar Cliente:");

        for (Cliente c : clientes) {
            Integer id = c.getIdCliente();
            String nombre = c.getPersona().getNombre() + " " + c.getPersona().getApellido();
            listaClientes.add(new AbstractMap.SimpleEntry<>(id, nombre));
            jcbCliente.addItem(nombre);
        }

        if (!listenerClienteInstalado) {
            jcbCliente.addActionListener(e -> enClienteSeleccionado());
            listenerClienteInstalado = true;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcbCliente;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JPanel jpDatosCuentaCorriente;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDatosCuenta;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbLimiteDeCredito;
    private javax.swing.JLabel lbSaldoInicial;
    private javax.swing.JLabel lbUsuarioBusqueda;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLista;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tableCCClientes;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtLimiteDeCredito;
    private javax.swing.JTextField txtSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
