
package veterinaria.vista;

import java.awt.BorderLayout;
import javax.swing.SwingConstants;
import veterinaria.util.PermisoUI;

public class FormAccesoRestringido extends javax.swing.JPanel {

    public FormAccesoRestringido() {
        initComponents();
        PermisoUI.aplicar(this);
        setLayout(new BorderLayout());
        lbRestringido.setHorizontalAlignment(SwingConstants.CENTER);
        add(lbRestringido, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRestringido = new javax.swing.JLabel();

        lbRestringido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbRestringido.setText("Acceso Restringido: No tiene los permisos necesarios para realizar esta acción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(lbRestringido)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lbRestringido, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(225, 225, 225))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbRestringido;
    // End of variables declaration//GEN-END:variables
}
