package veterinaria.vista;

import java.util.Arrays;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import veterinaria.controlador.ProductoControlador;
import veterinaria.controlador.ProveedorControlador;
import veterinaria.entidad.Producto;
import veterinaria.entidad.Proveedor;
import veterinaria.entidad.util.ProveedorItem;
import veterinaria.reportes.core.ReporteRequest;
import veterinaria.reportes.core.ReporteTipo;
import veterinaria.reportes.pdf.ReporteSelectorUtil;
import static veterinaria.util.Constantes.*;
import veterinaria.util.ManejoTablas;
import veterinaria.util.SesionUsuario;
import veterinaria.util.Validaciones;
import veterinaria.vista.application.Application;
import veterinaria.util.PermisoUI;
import veterinaria.servicio.RubroService;
import veterinaria.util.ModeloTablaGenerico;

public class FormProducto extends javax.swing.JPanel {

    private final ProductoControlador operandoProducto = new ProductoControlador();
    private final ProveedorControlador operandoProveedor = new ProveedorControlador();
    private final ManejoTablas operarTablas = new ManejoTablas();
    private ModeloTablaGenerico<Producto> modeloProductos;
    private final Validaciones validar = new Validaciones();
    private Proveedor proveedor = new Proveedor();
    private Producto producto = new Producto();
    private SesionUsuario sesion = Application.getSesionUsuario();
    private final RubroService rubroService = new RubroService();
    private boolean listenerSeleccionUnicaInstalado = false;
    private final java.awt.event.ActionListener proveedorComboActionListener = e -> onProveedorSeleccionado();

    public FormProducto() {
        initComponents();
        PermisoUI.aplicar(this);
        tableProductos.getTableHeader().setReorderingAllowed(false);
        initListeners();
        cargarCombosBoxs();
        cargarComboEstadoProducto();
        // En cualquier otro formulario (ej. FormProducto, FormMascota, etc.)
        operarTablas.ocultarColumnaId(tableProductos, 1);

        // Validaciones de ingreso (evita NumberFormatException al guardar)
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validar.validarSoloNumerosConDecimal(evt, txtPrecio);
            }
        });
        txtStockInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validar.validarSoloNumeros(evt);
            }
        });
        txtStockMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validar.validarSoloNumeros(evt);
            }
        });

        jpDatosProducto.setVisible(false);
        cargarProductosEnTabla();
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);

        // PDF
        btnImprimir.setVisible(false);
        btnImprimirLista.addActionListener(evt -> btnImprimirListaActionPerformed(evt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHadear = new javax.swing.JPanel();
        lbProveedores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelBotones = new javax.swing.JPanel();
        lbUsuarioBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbBuscar = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jcbEstadoProducto = new javax.swing.JComboBox<>();
        lbEstado = new javax.swing.JLabel();
        jpDatosProducto = new javax.swing.JPanel();
        lbIva = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lbDescripcion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        lbDatosPersonales = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbDescuento = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        lbRubro = new javax.swing.JLabel();
        jcbRubro = new javax.swing.JComboBox<>();
        lbUnidadDeMedida = new javax.swing.JLabel();
        jcbUMedida = new javax.swing.JComboBox<>();
        lbProveedor = new javax.swing.JLabel();
        jcbProveedor = new javax.swing.JComboBox<>();
        jcbIva = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lbProveedor1 = new javax.swing.JLabel();
        lbPrecios = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        lbCodigo1 = new javax.swing.JLabel();
        txtStockInicial = new javax.swing.JTextField();
        lbCodigo2 = new javax.swing.JLabel();
        jpListaProductos = new javax.swing.JPanel();
        lbListProd = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        tableProductos = new veterinaria.vista.table.AutoTable();
        btnImprimirLista = new javax.swing.JButton();

        lbProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbProveedores.setText("Productos");

        javax.swing.GroupLayout panelHadearLayout = new javax.swing.GroupLayout(panelHadear);
        panelHadear.setLayout(panelHadearLayout);
        panelHadearLayout.setHorizontalGroup(
            panelHadearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHadearLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbProveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHadearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        panelHadearLayout.setVerticalGroup(
            panelHadearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHadearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        lbUsuarioBusqueda.setText("BUSCAR PRODUCTO");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/icon/png/search.png"))); // NOI18N

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lbEstado.setText("Estado:");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbUsuarioBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbEstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbUsuarioBusqueda)
                            .addComponent(lbEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbEstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpDatosProducto.setMinimumSize(new java.awt.Dimension(600, 76));

        lbIva.setText("IVA: *");

        lbDescripcion.setText("Descripción:");

        lbNombre.setText("Nombre: *");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        lbCodigo.setText("Código: *");

        lbDatosPersonales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDatosPersonales.setText("Información de los Productos");

        lbDescuento.setText("Descuento: ");

        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        lbRubro.setText("Rubro:*");

        lbUnidadDeMedida.setText("Unidad de Medida:");

        lbProveedor.setText("Proveedor: *");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbProveedor1.setText("Estado: *");

        lbPrecios.setText("Precio: *");

        lbCodigo1.setText("Stock Inicial:*");

        lbCodigo2.setText("Stock Mínimo:*");

        javax.swing.GroupLayout jpDatosProductoLayout = new javax.swing.GroupLayout(jpDatosProducto);
        jpDatosProducto.setLayout(jpDatosProductoLayout);
        jpDatosProductoLayout.setHorizontalGroup(
            jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbIva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbIva)
                                            .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbCodigo2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbUnidadDeMedida)
                                                    .addComponent(jcbUMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbProveedor)
                                                    .addComponent(jcbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbProveedor1)
                                                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosProductoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbNombre)
                                                .addGap(95, 95, 95)))
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbRubro)
                                            .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDescripcion)
                                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbPrecios)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbDatosPersonales)))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDatosProductoLayout.setVerticalGroup(
            jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                .addComponent(lbDatosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addComponent(lbRubro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(lbNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addComponent(lbDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addComponent(lbPrecios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescuento)
                            .addComponent(lbIva, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbProveedor)
                            .addComponent(lbProveedor1)
                            .addComponent(lbUnidadDeMedida))
                        .addGap(6, 6, 6)
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jcbUMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jpDatosProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpDatosProductoLayout.createSequentialGroup()
                                .addGroup(jpDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCodigo2)
                                    .addComponent(lbCodigo1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbListProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbListProd.setText("Lista de Productos");

        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seleccionar", "ID", "Código", "Nombre", "Rubro", "Descripción", "Precio Costo", "Precio Venta", "Unidad de Medida", "Stock Actual", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductos.setMinimumSize(new java.awt.Dimension(848, 220));
        tableProductos.setPreferredSize(new java.awt.Dimension(848, 220));
        tableProductos.getTableHeader().setReorderingAllowed(false);
        scroll.setViewportView(tableProductos);

        btnImprimirLista.setText("Imprimir Lista");
        btnImprimirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        javax.swing.GroupLayout jpListaProductosLayout = new javax.swing.GroupLayout(jpListaProductos);
        jpListaProductos.setLayout(jpListaProductosLayout);
        jpListaProductosLayout.setHorizontalGroup(
            jpListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbListProd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimirLista)
                .addContainerGap())
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addGroup(jpListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListaProductosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)))
        );
        jpListaProductosLayout.setVerticalGroup(
            jpListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbListProd)
                    .addComponent(btnImprimirLista))
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
            .addGroup(jpListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpListaProductosLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpListaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHadear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHadear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jpDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpListaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Application.actualizarEstadoUsuario("CreandoProducto");
        limpiarCamposFormulario();
        txtCodigo.setEnabled(true);
        jpDatosProducto.setVisible(true);
        jpListaProductos.setVisible(false);
        panelBotones.setVisible(false);
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnImprimir.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String perm = "FormProducto.EDITAR";
        if (sesion == null || !sesion.puede(perm)) {
            JOptionPane.showMessageDialog(
                    null,
                    "No tienes permisos suficientes para editar productos.",
                    "Acceso restringido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (!editarProductoSeleccionado()) {
            return;
        }

        Application.actualizarEstadoUsuario("EditandoProducto");
        jpDatosProducto.setVisible(true);
        jpListaProductos.setVisible(false);
        panelBotones.setVisible(false);
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnImprimir.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String perm = "FormProducto.ELIMINAR";
        if (sesion == null || !sesion.puede(perm)) {
            JOptionPane.showMessageDialog(
                    null,
                    "No tienes permisos suficientes para eliminar productos.",
                    "Acceso restringido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Application.actualizarEstadoUsuario("EliminandoProducto");

        // Obtenemos el producto seleccionado de la tabla solo para mostrar su nombre en la confirmación
        Producto seleccionado = obtenerProductoSeleccionadoDesdeTabla();
        if (seleccionado == null) {
            return;
        }

        if (!confirmarEliminacionProducto(seleccionado)) {
            Application.actualizarEstadoUsuario("Eliminación cancelada");
            return;
        }

        // Delegamos la eliminación al método que interactúa con el controlador
        if (eliminarProductoSeleccionado()) {
            JOptionPane.showMessageDialog(null, "Producto eliminado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
            mostrarPanelLista();
            return;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void btnImprimirListaActionPerformed(java.awt.event.ActionEvent evt) {
        if (tableProductos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos en la tabla para exportar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Desplegamos el Pop-up para elegir el filtro de impresión
        JPopupMenu menuFiltro = new JPopupMenu();

        JMenuItem itemTodos = new JMenuItem("Todos los Productos");
        itemTodos.addActionListener(e -> solicitarFormatoEImprimir("TODOS"));
        menuFiltro.add(itemTodos);

        menuFiltro.addSeparator();

        // Cargamos los rubros activos dinámicamente desde el servicio
        try {
            List<String> rubrosDb = rubroService.listarNombresActivos();
            if (rubrosDb != null) {
                for (String rubro : rubrosDb) {
                    if (rubro != null && !rubro.trim().isEmpty()) {
                        JMenuItem itemRubro = new JMenuItem("Rubro: " + rubro.trim());
                        itemRubro.addActionListener(e -> solicitarFormatoEImprimir(rubro.trim()));
                        menuFiltro.add(itemRubro);
                    }
                }
            }
        } catch (Exception ex) {
            System.err.println("Error al cargar rubros para el menú: " + ex.getMessage());
        }

        menuFiltro.show(btnImprimirLista, 0, btnImprimirLista.getHeight());
    }
    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        validar.validarSoloNumeros(evt);
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        normalizarCamposProducto();

        // Construimos el objeto con los datos de la interfaz
        Producto p = construirProductoDesdeFormulario();
        String estadoActual = Application.consultarEstadoUsuario();
        boolean esNuevo = "CreandoProducto".equals(estadoActual);

        // Confirmaciones visuales mediante JOptionPane
        if (esNuevo && !confirmarAltaProducto()) {
            return;
        }
        if (!esNuevo && !confirmarEdicionProducto()) {
            return;
        }

        try {
            // Delegamos todo al controlador/capa de negocio (Aquí se calcula el precio y se guarda)
            String codigoOriginal = esNuevo ? "" : p.getCodigo();
            boolean exito = operandoProducto.validarYGuardarProducto(p, esNuevo, codigoOriginal);

            if (exito) {
                // Mensaje de éxito correspondiente
                JOptionPane.showMessageDialog(this, esNuevo ? "Producto guardado exitosamente." : "Producto editado exitosamente.");

                // --- ACCIONES POST-GUARDADO EXITOSO (Recuperadas de tu versión anterior) ---
                limpiarCamposFormulario();
                cargarProductosEnTabla();

                // Manejo de paneles (puedes usar tu método mostrarPanelLista() o las líneas manuales)
                mostrarPanelLista();

                // Restablecer estados de botones si tu lógica lo requiere
                btnNuevo.setEnabled(true);
                btnEditar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnImprimir.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IllegalArgumentException ex) {
            // Capturamos cualquier regla de negocio rota (incluyendo el Logger si ocurre en el controlador)
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCamposFormulario();
        mostrarPanelLista();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCamposFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        validar.validarSoloNumerosConDecimal(evt, txtDescuento);
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        imprimirRegistroSeleccionado();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none
    private void imprimirRegistroSeleccionado() {
        Producto p = obtenerProductoSeleccionadoDesdeTabla();
        if (p == null) {
            return;
        }

        // 1. Armamos los parámetros para el reporte del producto
        ReporteRequest req = new ReporteRequest()
                .put("producto", p)
                .put("emisor", Application.getNombreApellidoUsuarioLogeado());

        // 2. 🚀 AL EJECUTOR: Sin "new", usa el Singleton en segundo plano con barra de progreso
        veterinaria.reportes.pdf.ReporteEjecutor.ejecutarConAviso(this, ReporteTipo.PRODUCTO_REGISTRO, req);
    }

    private void solicitarFormatoEImprimir(String rubroFiltro) {
        ReporteSelectorUtil.Formato formato = ReporteSelectorUtil.solicitarFormato(this);
        if (formato == null) {
            return;
        }
        imprimirListaProductosConFiltro(formato, rubroFiltro);
    }

    private void imprimirListaProductosConFiltro(ReporteSelectorUtil.Formato formato, String rubroFiltro) {
        ReporteRequest req = new ReporteRequest()
                .put("tabla", tableProductos)
                .put("emisor", Application.getNombreApellidoUsuarioLogeado())
                .put("rubroFiltro", rubroFiltro) // 🌟 Asegúrate de que coincida con el que lee el PDF
                .put("FORMATO_REPORTE", formato);

        veterinaria.reportes.pdf.ReporteEjecutor.ejecutarConAviso(this, ReporteTipo.PRODUCTO_LISTADO, req);
    }

    private Producto obtenerProductoSeleccionadoDesdeTabla() {
        int row = operarTablas.comprobarElementoSeleccionado(tableProductos);
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un producto de la lista.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return null;
        }

        Object idObj = tableProductos.getValueAt(row, 1);
        Integer id = null;
        try {
            id = Integer.valueOf(String.valueOf(idObj));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo obtener el ID del producto seleccionado.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }

        Producto p = operandoProducto.buscarProductoPorId(id);
        if (p == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró el producto seleccionado en la base de datos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return p;
    }

    private double obtenerDescuentoNormalizado() {
        String descuentoTexto = txtDescuento.getText() != null ? txtDescuento.getText().trim() : "";
        if (descuentoTexto.isEmpty()) {
            return 0d;
        }
        descuentoTexto = descuentoTexto.replace(",", ".");
        return Double.parseDouble(descuentoTexto);
    }

    private String obtenerDescuentoParaPersistencia() {
        double descuento = obtenerDescuentoNormalizado();
        if (descuento == Math.rint(descuento)) {
            return String.valueOf((long) descuento);
        }
        return String.valueOf(descuento);
    }

    private boolean eliminarProductoSeleccionado() {
        Integer selectedRow = operarTablas.comprobarElementoSeleccionado(tableProductos);
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto a ELIMINAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // Obtenemos el ID de la tabla (asegúrate de que el índice de columna de tu ID sea el correcto, ej: 1)
        Integer idProducto = (Integer) tableProductos.getValueAt(selectedRow, 1);

        // Delegamos la operación al controlador que ya creamos
        boolean exito = operandoProducto.eliminarProductoPorId(idProducto);

        if (!exito) {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el producto seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return exito;
    }

    private boolean editarProductoSeleccionado() {
        int selectedRow = operarTablas.comprobarElementoSeleccionado(tableProductos);
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "¡Debe seleccionar un producto a EDITAR!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // Leemos la celda del ID de forma segura (asegúrate de que el índice '1' sea el de la columna ID)
        Object valorId = tableProductos.getValueAt(selectedRow, 1);
        if (valorId == null) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el identificador del producto.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Convertimos a String primero y luego a Integer para evitar cualquier ClassCastException
        Integer idProducto = Integer.valueOf(valorId.toString().trim());

        // Buscamos en el controlador usando el método que ya tienes
        producto = operandoProducto.buscarProductoPorId(idProducto);

        if (producto == null) {
            JOptionPane.showMessageDialog(null, "No se encontró el producto en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Asignación de campos al formulario...
        proveedor = producto.getProveedor();
        txtCodigo.setText(producto.getCodigo());
        txtCodigo.setEnabled(false);
        txtNombre.setText(producto.getNombre());
        jcbRubro.setSelectedItem(producto.getRubro());
        txtDescripcion.setText(producto.getDescripcion());
        txtPrecio.setText(String.valueOf(producto.getPrecioCosto()));
        jcbIva.setSelectedItem(String.valueOf(producto.getIva()));
        txtDescuento.setText(String.valueOf(producto.getDescuento() != null ? producto.getDescuento() : "0"));
        jcbUMedida.setSelectedItem(producto.getUmedida());
        seleccionarProveedorEnCombo(producto.getProveedor() != null ? producto.getProveedor().getIdProveedor() : null);
        jcbEstado.setSelectedItem(producto.getEstado());
        txtStockInicial.setText(String.valueOf(producto.getStock() != null ? producto.getStock() : 0));
        txtStockMinimo.setText(String.valueOf(producto.getStockMinimo() != null ? producto.getStockMinimo() : 0));

        return true;
    }

    private Double parseDoublePrecio(String raw) {
        if (raw == null) {
            return 0.0;
        }
        // Normaliza coma decimal a punto
        String v = raw.trim().replace(" ", "").replace(",", ".");
        return Double.valueOf(v);
    }

    private void cargarComboEstadoProducto() {
        jcbEstadoProducto.removeAllItems();
        jcbEstadoProducto.addItem("Todos");
        jcbEstadoProducto.addItem("Activos");
        jcbEstadoProducto.addItem("Eliminados");
        jcbEstadoProducto.setSelectedItem("Activos");
    }

    private String obtenerFiltroEstadoProductoSeleccionado() {
        Object estadoSeleccionado = jcbEstadoProducto.getSelectedItem();
        return estadoSeleccionado != null ? estadoSeleccionado.toString().trim() : "Activos";
    }

    private void cargarCombosBoxs() {
        txtStockInicial.setText("0");
        txtStockMinimo.setText("0");
        txtDescuento.setText("0");

        jcbRubro.removeAllItems();
        jcbRubro.addItem("Seleccionar Rubro");
        try {
            List<String> rubrosDb = rubroService.listarNombresActivos();
            if (rubrosDb != null && !rubrosDb.isEmpty()) {
                for (String r : rubrosDb) {
                    if (r != null && !r.trim().isEmpty()) {
                        jcbRubro.addItem(r.trim());
                    }
                }
            }
        } catch (Exception ex) {
            System.err.println("Error al cargar rubros: " + ex.getMessage());
        }

        jcbEstado.removeAllItems();
        jcbEstado.addItem(TEXT_ESTADO_SELECTION);
        jcbEstado.addItem(TEXT_ESTADO_ACTIVO);
        jcbEstado.addItem(TEXT_ESTADO_INACTIVO);

        jcbUMedida.removeAllItems();
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_SELECTION);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_UNIDAD);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_CAJA);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_LITROS);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_MILIMETROS);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_KILOGRAMOS);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_PAQUETE);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_FRASCO);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_BOTELLA);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_AMPOLLA);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_SACHET);
        jcbUMedida.addItem(TEXT_UNIDADMEDIDA_TABLET);

        jcbIva.removeAllItems();
        jcbIva.addItem(TEXT_IVA_SELECTION);
        jcbIva.addItem(TEXT_IVA_21);
        jcbIva.addItem(TEXT_IVA_105);
        jcbIva.addItem(TEXT_IVA_00);

        jcbProveedor.removeActionListener(proveedorComboActionListener);
        jcbProveedor.removeAllItems();
        List<Proveedor> listaProveedores = operandoProveedor.buscarTodosLosProveedores();
        ProveedorItem proveedorItem = new ProveedorItem(0, "Seleccionar Proveedor");
        jcbProveedor.addItem(proveedorItem);

        for (Proveedor proveedorBucle : listaProveedores) {
            String nombreProveedor = proveedorBucle.getRazonSocial();
            proveedorItem = new ProveedorItem(proveedorBucle.getIdProveedor(), nombreProveedor);
            jcbProveedor.addItem(proveedorItem);
        }
        jcbProveedor.addActionListener(proveedorComboActionListener);
    }

    private void onProveedorSeleccionado() {
        proveedor = obtenerProveedorSeleccionado();
    }

    private void cargarProductosEnTabla() {
        String filtroEstado = obtenerFiltroEstadoProductoSeleccionado();
        List<Producto> productos;

        if ("Todos".equalsIgnoreCase(filtroEstado)) {
            productos = operandoProducto.buscarTodosLosProductos();
        } else {
            productos = operandoProducto.buscarProductosPorEstado(filtroEstado);
        }

        // Configuración del formateador numérico para Argentina ($ 2.000,00)
        java.text.DecimalFormatSymbols simbolos = new java.text.DecimalFormatSymbols(new java.util.Locale("es", "AR"));
        simbolos.setGroupingSeparator('.');
        simbolos.setDecimalSeparator(',');

        java.text.DecimalFormat formateador = new java.text.DecimalFormat();
        formateador.setDecimalFormatSymbols(simbolos);
        formateador.applyPattern("$ #,##0.00");
        formateador.setGroupingUsed(true);

        // Si aún no inicializaste el modelo en el constructor, puedes inicializarlo aquí una vez o tenerlo como variable global.
        // Lo ideal es que modeloProductos sea un atributo de tu clase FormProducto.
        if (modeloProductos == null) {
            String[] columnas = {
                "Seleccionar", "ID", "Código", "Nombre", "Rubro", "Descripción", "Precio Costo", "Precio Venta", "Unidad de Medida", "Stock Actual"
            };

            modeloProductos = operarTablas.configurarTablaGenerica(tableProductos, columnas, (productoBucle, columnIndex) -> {
                if (productoBucle == null) {
                    return null;
                }

                Double precioVentaMostrar = productoBucle.getPrecio();
                if (precioVentaMostrar == null && productoBucle.getPrecioCosto() != null) {
                    double costo = productoBucle.getPrecioCosto();
                    double iva = 21.0;
                    try {
                        if (productoBucle.getIva() != null) {
                            String ivaLimpio = productoBucle.getIva().replaceAll("[^0-9.]", "");
                            if (!ivaLimpio.isEmpty()) {
                                iva = Double.parseDouble(ivaLimpio);
                            }
                        }
                    } catch (Exception e) {
                        iva = 0.0;
                    }
                    precioVentaMostrar = Math.round((costo * (1 + (iva / 100))) * 100.0) / 100.0;
                } else if (precioVentaMostrar == null) {
                    precioVentaMostrar = 0.0;
                }

                Integer stockMostrar = productoBucle.getStock() != null ? productoBucle.getStock() : 0;

                String costoFormateado = formateador.format(productoBucle.getPrecioCosto() != null ? productoBucle.getPrecioCosto() : 0.0);
                String ventaFormateada = formateador.format(precioVentaMostrar);
                String unidadMostrar = productoBucle.getUmedida() != null ? productoBucle.getUmedida() : "";

                switch (columnIndex) {
                    case 1:
                        return productoBucle.getIdProducto();
                    case 2:
                        return productoBucle.getCodigo();
                    case 3:
                        return productoBucle.getNombre();
                    case 4:
                        return productoBucle.getRubro();
                    case 5:
                        return productoBucle.getDescripcion();
                    case 6:
                        return costoFormateado;
                    case 7:
                        return ventaFormateada;
                    case 8:
                        return unidadMostrar;
                    case 9:
                        return stockMostrar;
                    default:
                        return null;
                }
            });

            operarTablas.ocultarColumnaId(tableProductos, 1);
        }

        // Simplemente le pasamos la lista de productos al modelo genérico de forma limpia y segura
        modeloProductos.cargarDatos(productos);

        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnImprimir.setVisible(false);
        actualizarTabla();
    }

    private void actualizarTabla() {     // Método para asegurar solamente selección de 1 fila para operar.
        if (listenerSeleccionUnicaInstalado) {
            return;
        }

        tableProductos.getModel().addTableModelListener(e -> {
            if (e.getColumn() == 0) {
                int rowCount = tableProductos.getRowCount();
                for (int i = 0; i < rowCount; i++) {
                    Object valor = tableProductos.getValueAt(i, 0);
                    boolean seleccionado = valor instanceof Boolean && (Boolean) valor;
                    if (i != e.getFirstRow() && seleccionado) {
                        tableProductos.setValueAt(false, i, 0);
                    }
                }
            }
        });
        listenerSeleccionUnicaInstalado = true;
    }

    private void limpiarCamposFormulario() {
        txtCodigo.setText("");
        txtCodigo.setEnabled(true);
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtDescuento.setText("0");
        txtStockInicial.setText("0");
        txtStockMinimo.setText("0");
        proveedor = new Proveedor();
        producto = new Producto();
        btnImprimir.setVisible(false);
        tableProductos.clearSelection();
        cargarCombosBoxs();
    }

    private void normalizarCamposProducto() {
        txtCodigo.setText(txtCodigo.getText().trim());
        txtNombre.setText(txtNombre.getText().trim());
        txtDescripcion.setText(txtDescripcion.getText().trim());
        txtPrecio.setText(txtPrecio.getText().trim().replace(",", "."));
        txtDescuento.setText(txtDescuento.getText().trim().replace(",", "."));
        txtStockInicial.setText(txtStockInicial.getText().trim());
        txtStockMinimo.setText(txtStockMinimo.getText().trim());
    }

    private String valorCombo(javax.swing.JComboBox<?> combo) {
        Object item = combo.getSelectedItem();
        return item != null ? item.toString().trim() : "";
    }

    private Proveedor obtenerProveedorSeleccionado() {
        Object selProv = jcbProveedor.getSelectedItem();
        if (selProv instanceof ProveedorItem) {
            ProveedorItem pi = (ProveedorItem) selProv;
            if (pi.getIdProveedor() != null && pi.getIdProveedor() != 0) {
                return operandoProveedor.buscarProveedorPorId(pi.getIdProveedor());
            }
        }
        return null;
    }

    private void seleccionarProveedorEnCombo(Integer idProveedor) {
        if (idProveedor == null) {
            jcbProveedor.setSelectedIndex(0);
            return;
        }
        for (int i = 0; i < jcbProveedor.getItemCount(); i++) {
            ProveedorItem item = jcbProveedor.getItemAt(i);
            if (item != null && idProveedor.equals(item.getIdProveedor())) {
                jcbProveedor.setSelectedIndex(i);
                return;
            }
        }
        jcbProveedor.setSelectedIndex(0);
    }

    private Producto construirProductoDesdeFormulario() {
        Producto p = new Producto();

        // Recuperar ID si estamos editando
        if (this.producto != null && this.producto.getIdProducto() != null) {
            p.setIdProducto(this.producto.getIdProducto());
        }

        p.setCodigo(txtCodigo.getText().trim());
        p.setNombre(txtNombre.getText().trim());
        p.setRubro(valorCombo(jcbRubro));
        p.setDescripcion(txtDescripcion.getText().trim());

        try {
            // 1. Lo que ingresas en pantalla se guarda como Precio Costo
            p.setPrecioCosto(parseDoublePrecio(txtPrecio.getText()));
        } catch (Exception ex) {
            p.setPrecioCosto(0.0);
        }

        p.setIva(valorCombo(jcbIva));
        p.setDescuento(obtenerDescuentoParaPersistencia());
        p.setUmedida(valorCombo(jcbUMedida));
        p.setProveedor(obtenerProveedorSeleccionado());
        p.setEstado(valorCombo(jcbEstado));

        try {
            p.setStock(Integer.valueOf(txtStockInicial.getText().trim()));
        } catch (Exception ex) {
            p.setStock(0);
        }
        try {
            p.setStockMinimo(Integer.valueOf(txtStockMinimo.getText().trim()));
        } catch (Exception ex) {
            p.setStockMinimo(0);
        }

        return p;
    }

    private boolean confirmarAltaProducto() {
        Producto p = construirProductoDesdeFormulario();
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                construirResumenProducto(p, "¿Confirmar creación del producto?"),
                "Confirmar alta de producto",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        return respuesta == JOptionPane.YES_OPTION;
    }

    private boolean confirmarEdicionProducto() {
        Producto p = construirProductoDesdeFormulario();
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                construirResumenProducto(p, "¿Confirmar edición del producto?"),
                "Confirmar edición de producto",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        return respuesta == JOptionPane.YES_OPTION;
    }

    private boolean confirmarEliminacionProducto(Producto p) {
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                construirResumenProducto(p, "¿Estás seguro de que deseas eliminar este producto?"),
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        return respuesta == JOptionPane.YES_OPTION;
    }

    private String construirResumenProducto(Producto p, String encabezado) {
        String proveedorTexto = (p != null && p.getProveedor() != null && p.getProveedor().getRazonSocial() != null)
                ? p.getProveedor().getRazonSocial()
                : "Sin proveedor";

        return encabezado + "\n\n"
                + "Código: " + safe(p != null ? p.getCodigo() : null) + "\n"
                + "Nombre: " + safe(p != null ? p.getNombre() : null) + "\n"
                + "Rubro: " + safe(p != null ? p.getRubro() : null) + "\n"
                + "Descripción: " + safe(p != null ? p.getDescripcion() : null) + "\n"
                + "Precio: " + (p != null && p.getPrecioCosto() != null ? p.getPrecioCosto() : 0.0) + "\n"
                + "IVA: " + safe(p != null ? p.getIva() : null) + "\n"
                + "Descuento: " + safe(p != null ? p.getDescuento() : null) + "\n"
                + "Unidad de medida: " + safe(p != null ? p.getUmedida() : null) + "\n"
                + "Proveedor: " + proveedorTexto + "\n"
                + "Estado: " + safe(p != null ? p.getEstado() : null) + "\n"
                + "Stock inicial: " + (p != null && p.getStock() != null ? p.getStock() : 0) + "\n"
                + "Stock mínimo: " + (p != null && p.getStockMinimo() != null ? p.getStockMinimo() : 0);
    }

    private String safe(String valor) {
        return valor == null || valor.trim().isEmpty() ? "-" : valor.trim();
    }

    private void initListeners() {
        // SELECCIÓN VISUAL Y HABILITACIÓN DE BOTONES AL CLICKEAR FILA
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int viewRow = tableProductos.rowAtPoint(evt.getPoint());
                if (viewRow < 0) {
                    return;
                }

                // Habilita acciones sobre la fila seleccionada
                btnEditar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnImprimir.setVisible(true);

                // Selección visual en la tabla
                tableProductos.setRowSelectionInterval(viewRow, viewRow);

                // Opcional: Si querés que al hacer clic en cualquier parte de la fila 
                // se marque el checkbox automáticamente, descomenta estas líneas:
                /*
            int modelRow = tableProductos.convertRowIndexToModel(viewRow);
            ModeloTablaGenerico model = (ModeloTablaGenerico) tableProductos.getModel();
            model.setValueAt(true, modelRow, 0);
                 */
            }
        });

        jcbEstadoProducto.addActionListener(evt -> cargarProductosEnTabla());

        List<Integer> columnasObjetivo = Arrays.asList(2, 3, 5, 13);
        operarTablas.aplicarFiltroYResaltado(tableProductos, txtBusqueda, columnasObjetivo);
    }

    private void mostrarPanelLista() {
        jpDatosProducto.setVisible(false);
        jpListaProductos.setVisible(true);
        panelBotones.setVisible(true);
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnImprimir.setVisible(false);
        limpiarCamposFormulario();
        cargarProductosEnTabla();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimirLista;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbEstadoProducto;
    private javax.swing.JComboBox<String> jcbIva;
    private javax.swing.JComboBox<ProveedorItem> jcbProveedor;
    private javax.swing.JComboBox<String> jcbRubro;
    private javax.swing.JComboBox<String> jcbUMedida;
    private javax.swing.JPanel jpDatosProducto;
    private javax.swing.JPanel jpListaProductos;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbDatosPersonales;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDescuento;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbIva;
    private javax.swing.JLabel lbListProd;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecios;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbProveedor1;
    private javax.swing.JLabel lbProveedores;
    private javax.swing.JLabel lbRubro;
    private javax.swing.JLabel lbUnidadDeMedida;
    private javax.swing.JLabel lbUsuarioBusqueda;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelHadear;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockInicial;
    private javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables
}
