vetpro.db.url=jdbc:mysql://localhost:3306/veterinaria?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
vetpro.db.user=root
vetpro.db.password=
vetpro.hibernate.hbm2ddl=update
vetpro.hibernate.show_sql=false