@accentColor=$App.accent.orange

h1.font=bold +12

Component.focusWidth=1
Component.arc=10
Button.arc=10
Button.margin=4,6,4,6
ButtonForm.margin=5,5,5,5
TextComponent.arc=10
TextField.margin=4,6,4,6
PasswordField.margin=4,6,4,6
ComboBox.padding=4,6,4,6
FormattedTextField.margin=5,5,5,5
TextFieldForm.margin=5,5,5,5
ComboBoxForm.padding=5,5,5,5
TextArea.margin=3,1,3,1

Menu.header.font=$h2.font
Menu.label.font=14
Menu.foreground=#FFFFFF
Menu.scroll.width=5
Menu.scroll.trackInsets=2,0,2,1
Menu.scroll.thumbInsets=$Menu.scroll.trackInsets
Menu.icon.lightColor=rgb(240,240,240)
Menu.icon.darkColor=rgb(150,150,150)

TitlePane.unifiedBackground=false
TitlePane.buttonSize=35,23

TableHeader.height=28
Table.rowHeight=30
Table.cellFocusColor=null

ScrollBar.trackArc=999
ScrollBar.thumbArc=999
ScrollPane.TextComponent.arc=10

Popup.dropShadowInsets = 2,5,8,8

Toast.background=lighten(@background,5%)

AccentControl.show=false